from fastapi import FastAPI, Request, Form
from fastapi.responses import HTMLResponse
from fastapi.templating import Jinja2Templates
from fastapi.staticfiles import StaticFiles
from dotenv import load_dotenv
import os

# Load environment variables
load_dotenv()

# Create FastAPI application
app = FastAPI(
    title="LegalEaseAI",
    description="AI-Powered Legal Document Generator",
    version="1.0.0"
)

# Templates
templates = Jinja2Templates(directory="templates")

# Static files
app.mount(
    "/static",
    StaticFiles(directory="static"),
    name="static"
)


# -----------------------------
# Home Page
# -----------------------------
@app.get("/", response_class=HTMLResponse)
async def home(request: Request):

    return templates.TemplateResponse(
        "index.html",
        {
            "request": request
        }
    )


# -----------------------------
# Generate Legal Document
# -----------------------------
@app.post("/generate", response_class=HTMLResponse)
async def generate_document(
    request: Request,
    document_type: str = Form(...),
    parties: str = Form(...),
    terms: str = Form(...),
    effective_date: str = Form(...)
):

    prompt = f"""
You are a legal document drafting assistant.

Create a clear and professional legal document draft.

Document Type:
{document_type}

Parties Involved:
{parties}

Terms and Conditions:
{terms}

Effective Date:
{effective_date}

Instructions:
1. Give the document a suitable title.
2. Include the parties involved.
3. Include the effective date.
4. Organize the document into clear sections.
5. Include the provided terms and conditions.
6. Use professional language.
7. Include signature sections.
8. Do not invent important information.
9. Add a legal disclaimer.

Generate only the legal document.
"""

    generated_document = generate_with_ai(
        prompt,
        document_type,
        parties,
        terms,
        effective_date
    )

    return templates.TemplateResponse(
        "result.html",
        {
            "request": request,
            "document_type": document_type,
            "generated_document": generated_document
        }
    )


# -----------------------------
# AI Generation
# -----------------------------
def generate_with_ai(
    prompt,
    document_type,
    parties,
    terms,
    effective_date
):

    api_key = os.getenv("GEMINI_API_KEY")

    # Demo mode if API key is not available
    if not api_key:
        return create_demo_document(
            document_type,
            parties,
            terms,
            effective_date
        )

    try:

        from google import genai

        client = genai.Client(
            api_key=api_key
        )

        response = client.models.generate_content(
            model="gemini-2.5-flash",
            contents=prompt
        )

        return response.text

    except Exception as error:

        print("AI Error:", error)

        return create_demo_document(
            document_type,
            parties,
            terms,
            effective_date
        )


# -----------------------------
# Demo Document
# -----------------------------
def create_demo_document(
    document_type,
    parties,
    terms,
    effective_date
):

    return f"""
==================================================
              {document_type.upper()}
==================================================

LEGAL DOCUMENT

Effective Date:
{effective_date}

PARTIES
--------------------------------------------------

{parties}

TERMS AND CONDITIONS
--------------------------------------------------

{terms}

AGREEMENT
--------------------------------------------------

The parties agree to the terms and conditions
specified in this document.

The information provided by the user has been
used to create this basic legal document draft.

SIGNATURES
--------------------------------------------------

Party 1 Signature: __________________________

Name: ______________________________________

Date: ______________________________________


Party 2 Signature: __________________________

Name: ______________________________________

Date: ______________________________________


DISCLAIMER
--------------------------------------------------

This document was generated by LegalEaseAI for
educational and informational purposes.

It should be reviewed by a qualified legal
professional before official use.

==================================================
                 LegalEaseAI
==================================================
"""


# -----------------------------
# Run Application
# -----------------------------
if __name__ == "__main__":

    import uvicorn

    uvicorn.run(
        "app:app",
        host="127.0.0.1",
        port=8000,
        reload=True
    )
